// Code generated by custom_test; DO NOT EDIT.
// Source: tests/api/case.md
//
// 集成测试：连本地 MySQL 验证 ApiReward.List（领取列表）的权限解析 + 归属/排序。
// 直接构造 ListRewardReq 调 List(req)，跑通 ResolveElder + ListByUser 整条链路。
// 本地无 DB 时全部 t.Skip，保证 CI 无 DB 环境不挂。

package api_test

import (
	"errors"
	"os"
	"testing"

	wferrors "warm-nest/pkg/app/errors"
	"warm-nest/pkg/app/web/session"
	"warm-nest/pkg/tool/database/mysqls"
	"warm-nest/pkg/tool/database/mysqls/widgets"

	"warm-nest/internal/api"
	"warm-nest/internal/constant"
	"warm-nest/internal/model"
)

const testDSN = "root:123456@tcp(127.0.0.1:3306)/warm-nest?charset=utf8&parseTime=True&loc=Local"

// dbReady 标记本地 DB 是否可用；false 时所有用例 t.Skip。
var dbReady bool

func TestMain(m *testing.M) {
	// 切到项目根：业务代码用相对路径加载 app.toml/app_local.toml（config 等）。
	// go test 默认 cwd 是包目录 tests/api，需回退两级到项目根，否则 MustLoad 找不到 app.toml。
	_ = os.Chdir("../..")

	if err := mysqls.EnableMysql(testDSN); err == nil && mysqls.DB() != nil {
		// 领取记录表 drop 重建：本地可能残留旧版表（缺 receiver_address 等列），
		// CreateModel 幂等只在表不存在时建、不补列，故先 drop 保证 schema 与当前 model 对齐。
		_ = mysqls.DB().Exec("DROP TABLE IF EXISTS t_reward_claim").Error
		_ = widgets.CreateModel("领取记录表", model.RewardClaim{})
		_ = widgets.CreateModel("守护关系表", model.Guardianship{}) // 幂等：已存在则跳过
		dbReady = true
	}
	os.Exit(m.Run())
}

// requireDB 本地无 DB 跳过，并在每个用例前清表保证隔离。
func requireDB(t *testing.T) {
	t.Helper()
	if !dbReady {
		t.Skip("local mysql unavailable, skip integration test")
	}
	for _, tbl := range []string{"t_guardianship", "t_reward_claim"} {
		if err := mysqls.DB().Exec("DELETE FROM " + tbl).Error; err != nil {
			t.Fatalf("clean table %s: %v", tbl, err)
		}
	}
}

// seedGuardianship 造一条守护关系（guardian 守护 elder）。
func seedGuardianship(t *testing.T, guardianId, elderId, status string) {
	t.Helper()
	g := &model.Guardianship{
		GuardianshipId: "g-" + guardianId + "-" + elderId,
		GuardianUserId: guardianId,
		ElderUserId:    elderId,
		Relation:       model.RelationMom,
		Status:         status,
		ActivatedAt:    1000,
	}
	if err := mysqls.DB().Create(g).Error; err != nil {
		t.Fatalf("seed guardianship: %v", err)
	}
}

// seedClaim 造一条领取记录（显式 createdAt 以验证倒序）。
func seedClaim(t *testing.T, claimId, elderId string, createdAt int64) {
	t.Helper()
	c := &model.RewardClaim{
		ClaimId:     claimId,
		ElderUserId: elderId,
		TaskKey:     "task-" + claimId,   // 随 claimId 唯一，避开 u_user_task_period 唯一索引
		PeriodKey:   "period-" + claimId, // 同上：同一老人多条记录需 task/period 互异
		RewardKind:  "EGG",
		RewardName:  "一盒鸡蛋",
		Quantity:    1,
	}
	c.Status = model.ClaimStatusPending
	c.CreatedAt = createdAt // autoCreateTime:milli 仅零值时自动填，显式赋值保留
	if err := mysqls.DB().Create(c).Error; err != nil {
		t.Fatalf("seed reward claim: %v", err)
	}
}

// listReq 构造 List 入参（viewer = 登录人，elderUserId = 前端入参）。
func listReq(viewer, elderUserId string) api.ListRewardReq {
	return api.ListRewardReq{
		Session:     session.Session{ReqUser: viewer},
		ElderUserId: elderUserId,
	}
}

// callList 调 List 并断言无错、断言返回类型为 []model.RewardClaim。
func callList(t *testing.T, viewer, elderUserId string) []model.RewardClaim {
	t.Helper()
	res, err := api.GetApiReward().List(listReq(viewer, elderUserId))
	if err != nil {
		t.Fatalf("List(%s,%s) unexpected error: %v", viewer, elderUserId, err)
	}
	list, ok := res.([]model.RewardClaim)
	if !ok {
		t.Fatalf("List result type = %T, want []model.RewardClaim", res)
	}
	return list
}

// assertCodeError 断言 err 是带指定 Code 的框架 CodeError。
func assertCodeError(t *testing.T, err error, wantCode string) {
	t.Helper()
	if err == nil {
		t.Fatalf("expected CodeError %s, got nil", wantCode)
	}
	var ce *wferrors.CodeError
	if !errors.As(err, &ce) {
		t.Fatalf("expected *errors.CodeError %s, got %T: %v", wantCode, err, err)
	}
	if ce.Code != wantCode {
		t.Fatalf("expected code %s, got %s (%s)", wantCode, ce.Code, ce.Msg)
	}
}

// IT-01 老人不传 elderUserId 查自己：返回全部记录、按 createdAt 倒序（新在前）
func TestRewardList_IT01_ElderSelfDescOrder(t *testing.T) {
	requireDB(t)
	const guardian, elder = "guardianA", "elderA"
	seedGuardianship(t, guardian, elder, model.GuardianshipStatusActive) // elder 有 ACTIVE 守护边
	seedClaim(t, "claim-old", elder, 1750000000000)
	seedClaim(t, "claim-new", elder, 1750000005000)

	list := callList(t, elder, "")
	if len(list) != 2 {
		t.Fatalf("IT-01 len = %d, want 2", len(list))
	}
	if list[0].ClaimId != "claim-new" || list[1].ClaimId != "claim-old" {
		t.Errorf("IT-01 order = [%s,%s], want [claim-new,claim-old] (created_at DESC)",
			list[0].ClaimId, list[1].ClaimId)
	}
}

// IT-02 子女传 elderUserId 查所守护老人：返回该老人记录、归属正确
func TestRewardList_IT02_GuardianViewElder(t *testing.T) {
	requireDB(t)
	const guardian, elder = "guardianB", "elderB"
	seedGuardianship(t, guardian, elder, model.GuardianshipStatusActive)
	seedClaim(t, "claim-b", elder, 1750000000000)

	list := callList(t, guardian, elder)
	if len(list) != 1 {
		t.Fatalf("IT-02 len = %d, want 1", len(list))
	}
	if list[0].ElderUserId != elder {
		t.Errorf("IT-02 elderUserId = %s, want %s", list[0].ElderUserId, elder)
	}
}

// IT-03 老人传自己 userId 作 elderUserId（elderUserId==viewer）：走查自己分支
func TestRewardList_IT03_ElderPassOwnId(t *testing.T) {
	requireDB(t)
	const guardian, elder = "guardianC", "elderC"
	seedGuardianship(t, guardian, elder, model.GuardianshipStatusActive)
	seedClaim(t, "claim-c", elder, 1750000000000)

	list := callList(t, elder, elder) // 传自己 id
	if len(list) != 1 || list[0].ClaimId != "claim-c" {
		t.Fatalf("IT-03 got %d records, want 1 (claim-c)", len(list))
	}
}

// IT-04 子女不传 elderUserId（误用：自身非被守护人）：ErrNotGuardian、不静默返空
func TestRewardList_IT04_GuardianNoElderIdRejected(t *testing.T) {
	requireDB(t)
	const guardian, elder = "guardianD", "elderD"
	seedGuardianship(t, guardian, elder, model.GuardianshipStatusActive)

	// guardian 不传 elderUserId：isElder(guardian)=false（它是守护人非被守护人）
	_, err := api.GetApiReward().List(listReq(guardian, ""))
	assertCodeError(t, err, constant.ErrNotGuardian.Code)
}

// IT-05 非守护人传他人 elderUserId（无 ACTIVE 守护关系）：ErrNotGuardian
func TestRewardList_IT05_NonGuardianRejected(t *testing.T) {
	requireDB(t)
	const stranger, elder = "strangerE", "elderE"
	seedClaim(t, "claim-e", elder, 1750000000000) // elder 有记录，但 stranger 无权看

	_, err := api.GetApiReward().List(listReq(stranger, elder))
	assertCodeError(t, err, constant.ErrNotGuardian.Code)
}

// IT-06 守护关系非 ACTIVE（INACTIVE）传该老人 elderUserId：ErrNotGuardian
func TestRewardList_IT06_InactiveGuardianRejected(t *testing.T) {
	requireDB(t)
	const guardian, elder = "guardianF", "elderF"
	seedGuardianship(t, guardian, elder, model.GuardianshipStatusInactive) // 已解除

	_, err := api.GetApiReward().List(listReq(guardian, elder))
	assertCodeError(t, err, constant.ErrNotGuardian.Code)
}

// IT-07 老人查自己但名下无任何领取记录：空列表、非 nil error
func TestRewardList_IT07_EmptyList(t *testing.T) {
	requireDB(t)
	const guardian, elder = "guardianG", "elderG"
	seedGuardianship(t, guardian, elder, model.GuardianshipStatusActive)

	list := callList(t, elder, "")
	if len(list) != 0 {
		t.Errorf("IT-07 len = %d, want 0", len(list))
	}
}

// IT-08 归属隔离：库内同时有 elderB 记录，查 elderA 仅返回 elderA 的
func TestRewardList_IT08_OwnershipIsolation(t *testing.T) {
	requireDB(t)
	const guardian, elderA, elderB = "guardianH", "elderHa", "elderHb"
	seedGuardianship(t, guardian, elderA, model.GuardianshipStatusActive)
	seedClaim(t, "claim-ha", elderA, 1750000000000)
	seedClaim(t, "claim-hb", elderB, 1750000000000) // 他人记录

	list := callList(t, elderA, "")
	if len(list) != 1 {
		t.Fatalf("IT-08 len = %d, want 1 (仅 elderA)", len(list))
	}
	if list[0].ElderUserId != elderA {
		t.Errorf("IT-08 leaked record of %s", list[0].ElderUserId)
	}
}
