// Code generated by custom_test; DO NOT EDIT.
// Source: tests/service/case.md
//
// 集成测试：连本地 MySQL 验证 InvitationService.Accept 的守卫逻辑。
// 本地无 DB 时全部 t.Skip，保证 CI 无 DB 环境不挂。

package service_test

import (
	"errors"
	"os"
	"testing"

	wferrors "warm-nest/pkg/app/errors"
	"warm-nest/pkg/tool/database/mysqls"
	"warm-nest/pkg/tool/database/mysqls/widgets"

	"warm-nest/internal/constant"
	"warm-nest/internal/mapper"
	"warm-nest/internal/model"
	"warm-nest/internal/service"
)

const testDSN = "root:123456@tcp(127.0.0.1:3306)/warm-nest?charset=utf8&parseTime=True&loc=Local"

// dbReady 标记本地 DB 是否可用；false 时所有用例 t.Skip。
var dbReady bool

func TestMain(m *testing.M) {
	// 切到项目根：业务代码用相对路径加载 app.toml/app_local.toml（config.WeChatConf 等）。
	// go test 默认 cwd 是包目录 tests/service，需回退两级到项目根，否则 MustLoad 找不到 app.toml。
	_ = os.Chdir("../..")

	if err := mysqls.EnableMysql(testDSN); err == nil && mysqls.DB() != nil {
		// 建表（幂等：已存在则跳过）+ 跑 activated_at 迁移
		_ = widgets.CreateModel("守护邀请表", model.Invitation{})
		_ = widgets.CreateModel("守护关系表", model.Guardianship{})
		_ = widgets.CreateModel("被守护人档案表", model.ElderProfile{})
		_ = widgets.CreateModel("小程序消息表", model.Message{})
		_ = widgets.AddColumnAfter(model.Guardianship{}, "ActivatedAt", "Status")
		// 与 migrate_center 对齐：补 invitation.city / elder_profile 联系电话列
		_ = widgets.AddColumnAfter(model.Invitation{}, "City", "RemindTime")
		_ = widgets.AddColumnAfter(model.ElderProfile{}, "ElderPhone", "Address")
		_ = widgets.AddColumnAfter(model.ElderProfile{}, "GuardianPhone", "ElderPhone")
		dbReady = true
	}
	os.Exit(m.Run())
}

// cleanTables 每个用例前清空相关表，保证用例间隔离。
func cleanTables(t *testing.T) {
	t.Helper()
	for _, tbl := range []string{"t_invitation", "t_guardianship", "t_elder_profile", "t_message"} {
		if err := mysqls.DB().Exec("DELETE FROM " + tbl).Error; err != nil {
			t.Fatalf("clean table %s: %v", tbl, err)
		}
	}
}

func requireDB(t *testing.T) {
	t.Helper()
	if !dbReady {
		t.Skip("local mysql unavailable, skip integration test")
	}
	cleanTables(t)
}

// seedInvitation 造一条邀请记录。
func seedInvitation(t *testing.T, inv *model.Invitation) {
	t.Helper()
	if err := mapper.GetInvitationMapper().Create(inv); err != nil {
		t.Fatalf("seed invitation: %v", err)
	}
}

// seedGuardianship 造一条守护关系。
func seedGuardianship(t *testing.T, guardianId, elderId, status string) {
	t.Helper()
	g := &model.Guardianship{
		GuardianshipId: "g-" + guardianId + "-" + elderId,
		GuardianUserId: guardianId,
		ElderUserId:    elderId,
		Relation:       model.RelationMom,
		Status:         status,
		ActivatedAt:    1000,
	}
	if err := mysqls.DB().Create(g).Error; err != nil {
		t.Fatalf("seed guardianship: %v", err)
	}
}

// assertCodeError 断言 err 是带指定 Code 的框架 CodeError。
func assertCodeError(t *testing.T, err error, wantCode string) {
	t.Helper()
	if err == nil {
		t.Fatalf("expected CodeError %s, got nil", wantCode)
	}
	var ce *wferrors.CodeError
	if !errors.As(err, &ce) {
		t.Fatalf("expected *errors.CodeError %s, got %T: %v", wantCode, err, err)
	}
	if ce.Code != wantCode {
		t.Fatalf("expected code %s, got %s (%s)", wantCode, ce.Code, ce.Msg)
	}
}

// IT-01 首次接受：建档案+关系(ActivatedAt==nowMs)+置邀请 ACCEPTED 回填
func TestAccept_IT01_FirstAccept(t *testing.T) {
	requireDB(t)
	const code, guardian, elder = "code01", "guardianA", "elderA"
	var nowMs int64 = 1750000000000
	seedInvitation(t, &model.Invitation{
		InvitationId:   "inv01",
		InviteCode:     code,
		GuardianUserId: guardian,
		Relation:       model.RelationDad,
		RemindTime:     "10:00",
		Status:         model.InvitationStatusPending,
		ExpireAt:       nowMs + 1000000,
	})

	if err := service.GetInvitationService().Accept(elder, code, nowMs); err != nil {
		t.Fatalf("IT-01 expected success, got %v", err)
	}

	// 断言守护关系
	g, err := mapper.GetGuardianshipMapper().GetActive(guardian, elder)
	if err != nil || g == nil {
		t.Fatalf("IT-01 guardianship not created: %v", err)
	}
	if g.Status != model.GuardianshipStatusActive {
		t.Errorf("IT-01 status = %s, want ACTIVE", g.Status)
	}
	if g.Relation != model.RelationDad {
		t.Errorf("IT-01 relation = %s, want DAD(邀请预设)", g.Relation)
	}
	if g.ActivatedAt != nowMs {
		t.Errorf("IT-01 ActivatedAt = %d, want %d", g.ActivatedAt, nowMs)
	}
	// 断言档案
	p, err := mapper.GetElderProfileMapper().GetByUserId(elder)
	if err != nil || p == nil {
		t.Fatalf("IT-01 elder profile not created: %v", err)
	}
	if p.RemindTime != "10:00" {
		t.Errorf("IT-01 remindTime = %s, want 10:00(邀请预设)", p.RemindTime)
	}
	// 断言邀请状态
	inv, _ := mapper.GetInvitationMapper().GetByInviteCode(code)
	if inv.Status != model.InvitationStatusAccepted {
		t.Errorf("IT-01 invitation status = %s, want ACCEPTED", inv.Status)
	}
	if inv.AcceptedElderUserId != elder || inv.AcceptedAt != nowMs {
		t.Errorf("IT-01 invitation backfill wrong: elder=%s at=%d", inv.AcceptedElderUserId, inv.AcceptedAt)
	}
}

// IT-02 同一老人重复接受已 ACCEPTED 的码：幂等返回 nil、不新增关系
func TestAccept_IT02_SameElderIdempotent(t *testing.T) {
	requireDB(t)
	const code, guardian, elder = "code02", "guardianB", "elderB"
	var nowMs int64 = 1750000000000
	seedInvitation(t, &model.Invitation{
		InvitationId: "inv02", InviteCode: code, GuardianUserId: guardian,
		Relation: model.RelationMom, RemindTime: "09:00",
		Status: model.InvitationStatusPending, ExpireAt: nowMs + 1000000,
	})
	if err := service.GetInvitationService().Accept(elder, code, nowMs); err != nil {
		t.Fatalf("IT-02 first accept failed: %v", err)
	}
	// 同一老人再接受
	if err := service.GetInvitationService().Accept(elder, code, nowMs+1); err != nil {
		t.Fatalf("IT-02 second accept (same elder) expected nil, got %v", err)
	}
	// 关系仍只有一条
	var cnt int64
	mysqls.DB().Model(&model.Guardianship{}).
		Where("guardian_user_id = ? AND elder_user_id = ?", guardian, elder).Count(&cnt)
	if cnt != 1 {
		t.Errorf("IT-02 guardianship count = %d, want 1", cnt)
	}
}

// IT-03 另一老人扫到已 ACCEPTED 的码：ErrInviteUsed，不建关系
func TestAccept_IT03_OtherElderRejected(t *testing.T) {
	requireDB(t)
	const code, guardian, elder1, elder2 = "code03", "guardianC", "elderC1", "elderC2"
	var nowMs int64 = 1750000000000
	seedInvitation(t, &model.Invitation{
		InvitationId: "inv03", InviteCode: code, GuardianUserId: guardian,
		Relation: model.RelationMom, RemindTime: "09:00",
		Status: model.InvitationStatusPending, ExpireAt: nowMs + 1000000,
	})
	if err := service.GetInvitationService().Accept(elder1, code, nowMs); err != nil {
		t.Fatalf("IT-03 first accept failed: %v", err)
	}
	// 另一老人扫同一码
	err := service.GetInvitationService().Accept(elder2, code, nowMs+1)
	assertCodeError(t, err, constant.ErrInviteUsed.Code)
	// elder2 没有任何关系
	g, _ := mapper.GetGuardianshipMapper().GetActive(guardian, elder2)
	if g != nil {
		t.Errorf("IT-03 elder2 should have no guardianship")
	}
}

// IT-04 老人已被别的子女绑定：ErrElderBound
func TestAccept_IT04_ElderBound(t *testing.T) {
	requireDB(t)
	const code, newGuardian, otherGuardian, elder = "code04", "guardianD", "guardianX", "elderD"
	var nowMs int64 = 1750000000000
	// elder 已被 otherGuardian 绑
	seedGuardianship(t, otherGuardian, elder, model.GuardianshipStatusActive)
	seedInvitation(t, &model.Invitation{
		InvitationId: "inv04", InviteCode: code, GuardianUserId: newGuardian,
		Relation: model.RelationMom, RemindTime: "09:00",
		Status: model.InvitationStatusPending, ExpireAt: nowMs + 1000000,
	})
	err := service.GetInvitationService().Accept(elder, code, nowMs)
	assertCodeError(t, err, constant.ErrElderBound.Code)
}

// IT-05 子女已绑别的老人：ErrGuardianBound
func TestAccept_IT05_GuardianBound(t *testing.T) {
	requireDB(t)
	const code, guardian, otherElder, newElder = "code05", "guardianE", "elderX", "elderE"
	var nowMs int64 = 1750000000000
	// guardian 已绑 otherElder
	seedGuardianship(t, guardian, otherElder, model.GuardianshipStatusActive)
	seedInvitation(t, &model.Invitation{
		InvitationId: "inv05", InviteCode: code, GuardianUserId: guardian,
		Relation: model.RelationMom, RemindTime: "09:00",
		Status: model.InvitationStatusPending, ExpireAt: nowMs + 1000000,
	})
	err := service.GetInvitationService().Accept(newElder, code, nowMs)
	assertCodeError(t, err, constant.ErrGuardianBound.Code)
}

// IT-06 接受 CANCELLED 邀请：ErrInviteState
func TestAccept_IT06_Cancelled(t *testing.T) {
	requireDB(t)
	const code, guardian, elder = "code06", "guardianF", "elderF"
	var nowMs int64 = 1750000000000
	seedInvitation(t, &model.Invitation{
		InvitationId: "inv06", InviteCode: code, GuardianUserId: guardian,
		Relation: model.RelationMom, RemindTime: "09:00",
		Status: model.InvitationStatusCancelled, ExpireAt: nowMs + 1000000,
	})
	err := service.GetInvitationService().Accept(elder, code, nowMs)
	assertCodeError(t, err, constant.ErrInviteState.Code)
}

// IT-07 接受 EXPIRED 邀请：ErrInviteState
func TestAccept_IT07_Expired(t *testing.T) {
	requireDB(t)
	const code, guardian, elder = "code07", "guardianG", "elderG"
	var nowMs int64 = 1750000000000
	seedInvitation(t, &model.Invitation{
		InvitationId: "inv07", InviteCode: code, GuardianUserId: guardian,
		Relation: model.RelationMom, RemindTime: "09:00",
		Status: model.InvitationStatusExpired, ExpireAt: nowMs + 1000000,
	})
	err := service.GetInvitationService().Accept(elder, code, nowMs)
	assertCodeError(t, err, constant.ErrInviteState.Code)
}

// IT-08 PENDING 但已超时(nowMs>ExpireAt)：ErrInviteState
func TestAccept_IT08_PendingOverdue(t *testing.T) {
	requireDB(t)
	const code, guardian, elder = "code08", "guardianH", "elderH"
	var nowMs int64 = 1750000000000
	seedInvitation(t, &model.Invitation{
		InvitationId: "inv08", InviteCode: code, GuardianUserId: guardian,
		Relation: model.RelationMom, RemindTime: "09:00",
		Status: model.InvitationStatusPending, ExpireAt: nowMs - 1, // 已过期
	})
	err := service.GetInvitationService().Accept(elder, code, nowMs)
	assertCodeError(t, err, constant.ErrInviteState.Code)
}

// IT-09 inviteCode 不存在：返回错误(非 CodeError，普通 not found)
func TestAccept_IT09_CodeNotFound(t *testing.T) {
	requireDB(t)
	err := service.GetInvitationService().Accept("elderI", "nonexistent-code", 1750000000000)
	if err == nil {
		t.Fatalf("IT-09 expected error for nonexistent code, got nil")
	}
}

// IT-10 该子女-老人对已存在 ACTIVE 关系、重复接受：幂等置 ACCEPTED、不新建第二条
func TestAccept_IT10_SamePairIdempotent(t *testing.T) {
	requireDB(t)
	const code, guardian, elder = "code10", "guardianJ", "elderJ"
	var nowMs int64 = 1750000000000
	// 该对已有 ACTIVE 关系
	seedGuardianship(t, guardian, elder, model.GuardianshipStatusActive)
	seedInvitation(t, &model.Invitation{
		InvitationId: "inv10", InviteCode: code, GuardianUserId: guardian,
		Relation: model.RelationMom, RemindTime: "09:00",
		Status: model.InvitationStatusPending, ExpireAt: nowMs + 1000000,
	})
	if err := service.GetInvitationService().Accept(elder, code, nowMs); err != nil {
		t.Fatalf("IT-10 expected idempotent success, got %v", err)
	}
	// 关系仍只有一条
	var cnt int64
	mysqls.DB().Model(&model.Guardianship{}).
		Where("guardian_user_id = ? AND elder_user_id = ?", guardian, elder).Count(&cnt)
	if cnt != 1 {
		t.Errorf("IT-10 guardianship count = %d, want 1", cnt)
	}
	// 邀请已置 ACCEPTED
	inv, _ := mapper.GetInvitationMapper().GetByInviteCode(code)
	if inv.Status != model.InvitationStatusAccepted {
		t.Errorf("IT-10 invitation status = %s, want ACCEPTED", inv.Status)
	}
}

// IT-11 首次接受且老人已有 ElderProfile：不重复建档案、建关系成功、ActivatedAt==nowMs
func TestAccept_IT11_ExistingProfile(t *testing.T) {
	requireDB(t)
	const code, guardian, elder = "code11", "guardianK", "elderK"
	var nowMs int64 = 1750000000000
	// 预先造一条 elder 档案
	if err := mysqls.DB().Create(&model.ElderProfile{
		UserId: elder, RealName: "张三", RemindTime: "08:00",
	}).Error; err != nil {
		t.Fatalf("IT-11 seed profile: %v", err)
	}
	seedInvitation(t, &model.Invitation{
		InvitationId: "inv11", InviteCode: code, GuardianUserId: guardian,
		Relation: model.RelationMom, RemindTime: "09:00",
		Status: model.InvitationStatusPending, ExpireAt: nowMs + 1000000,
	})
	if err := service.GetInvitationService().Accept(elder, code, nowMs); err != nil {
		t.Fatalf("IT-11 expected success, got %v", err)
	}
	// 档案仍只有一条、原 RealName 未被覆盖
	var cnt int64
	mysqls.DB().Model(&model.ElderProfile{}).Where("user_id = ?", elder).Count(&cnt)
	if cnt != 1 {
		t.Errorf("IT-11 elder profile count = %d, want 1 (不重复建)", cnt)
	}
	p, _ := mapper.GetElderProfileMapper().GetByUserId(elder)
	if p.RealName != "张三" {
		t.Errorf("IT-11 existing profile RealName overwritten: %s", p.RealName)
	}
	// 关系建成、ActivatedAt 正确
	g, _ := mapper.GetGuardianshipMapper().GetActive(guardian, elder)
	if g == nil || g.ActivatedAt != nowMs {
		t.Errorf("IT-11 guardianship wrong: %+v", g)
	}
}
