// Code generated by custom_test; DO NOT EDIT.
// Source: tests/reward/condition/case.md

package condition

import "testing"

func TestDaysInMonth(t *testing.T) {
	tests := []struct {
		id        string
		yearMonth string
		want      int
	}{
		{"DM01", "2026-07", 31},
		{"DM02", "2026-06", 30},
		{"DM03", "2026-02", 28},
		{"DM04", "2024-02", 29},
		{"DM05", "bad", 0},
	}
	for _, tt := range tests {
		t.Run(tt.id, func(t *testing.T) {
			if got := daysInMonth(tt.yearMonth); got != tt.want {
				t.Errorf("%s: daysInMonth(%q) = %d, want %d", tt.id, tt.yearMonth, got, tt.want)
			}
		})
	}
}

func TestFirstMonthRemaining(t *testing.T) {
	tests := []struct {
		id            string
		effectiveDate string
		yearMonth     string
		want          int
	}{
		{"FR01", "2026-06-01", "2026-06", 30},
		{"FR02", "2026-06-10", "2026-06", 21},
		{"FR03", "2026-06-16", "2026-06", 15},
		{"FR04", "2026-06-30", "2026-06", 1},
		{"FR05", "2026-05-10", "2026-06", 0},
		{"FR06", "", "2026-06", 0},
	}
	for _, tt := range tests {
		t.Run(tt.id, func(t *testing.T) {
			if got := firstMonthRemaining(tt.effectiveDate, tt.yearMonth); got != tt.want {
				t.Errorf("%s: firstMonthRemaining(%q, %q) = %d, want %d",
					tt.id, tt.effectiveDate, tt.yearMonth, got, tt.want)
			}
		})
	}
}

func TestMonthlyThreshold(t *testing.T) {
	tests := []struct {
		id            string
		effectiveDate string
		yearMonth     string
		wantThreshold int
		wantSkip      bool
	}{
		{"MT01", "2026-06-01", "2026-06", 27, false},
		{"MT02", "2026-06-10", "2026-06", 18, false},
		{"MT03", "2026-06-16", "2026-06", 12, false},
		{"MT04", "2026-06-17", "2026-06", 0, true},
		{"MT05", "2026-06-30", "2026-06", 0, true},
		{"MT06", "2026-05-10", "2026-06", 27, false},
		{"MT07", "", "2026-06", 27, false},
		{"MT08", "2026-02-01", "2026-02", 25, false},
		{"MT09", "2026-07-01", "2026-07", 28, false},
	}
	for _, tt := range tests {
		t.Run(tt.id, func(t *testing.T) {
			gotThreshold, gotSkip := monthlyThreshold(tt.effectiveDate, tt.yearMonth)
			if gotThreshold != tt.wantThreshold || gotSkip != tt.wantSkip {
				t.Errorf("%s: monthlyThreshold(%q, %q) = (%d, %v), want (%d, %v)",
					tt.id, tt.effectiveDate, tt.yearMonth, gotThreshold, gotSkip, tt.wantThreshold, tt.wantSkip)
			}
		})
	}
}
