// Code generated by custom_test; DO NOT EDIT.
// Source: tests/reward/condition/case.md

package condition

import "testing"

func TestCurrentStreak(t *testing.T) {
	tests := []struct {
		id    string
		dates []string
		today string
		want  int
	}{
		{"CS01", []string{}, "2026-06-15", 0},
		{"CS02", []string{"2026-06-15"}, "2026-06-15", 1},
		{"CS03", []string{"2026-06-13", "2026-06-14", "2026-06-15"}, "2026-06-15", 3},
		{"CS04", []string{"2026-06-13", "2026-06-14"}, "2026-06-15", 2},
		{"CS05", []string{"2026-06-10", "2026-06-14", "2026-06-15"}, "2026-06-15", 2},
		{"CS06", []string{"2026-06-13"}, "2026-06-15", 0},
		{"CS07", []string{"2026-06-15", "2026-06-13", "2026-06-14"}, "2026-06-15", 3},
		{"CS08", []string{"2026-06-15"}, "bad-date", 0},
		{"CS09", []string{"2026-06-14", "2026-06-14", "2026-06-15"}, "2026-06-15", 2},
	}
	for _, tt := range tests {
		t.Run(tt.id, func(t *testing.T) {
			if got := currentStreak(tt.dates, tt.today); got != tt.want {
				t.Errorf("%s: currentStreak(%v, %q) = %d, want %d", tt.id, tt.dates, tt.today, got, tt.want)
			}
		})
	}
}

func TestMonthDays(t *testing.T) {
	tests := []struct {
		id        string
		dates     []string
		yearMonth string
		want      int
	}{
		{"MD01", []string{}, "2026-06", 0},
		{"MD02", []string{"2026-06-01", "2026-06-02"}, "2026-06", 2},
		{"MD03", []string{"2026-05-31", "2026-06-01", "2026-06-02"}, "2026-06", 2},
		{"MD04", []string{"2026-06-01", "2026-06-01"}, "2026-06", 1},
		{"MD05", []string{"2026-05-01"}, "2026-06", 0},
		{"MD06", []string{"26-6"}, "2026-06", 0},
	}
	for _, tt := range tests {
		t.Run(tt.id, func(t *testing.T) {
			if got := monthDays(tt.dates, tt.yearMonth); got != tt.want {
				t.Errorf("%s: monthDays(%v, %q) = %d, want %d", tt.id, tt.dates, tt.yearMonth, got, tt.want)
			}
		})
	}
}

func TestCumulativeDays(t *testing.T) {
	tests := []struct {
		id    string
		dates []string
		want  int
	}{
		{"CD01", []string{}, 0},
		{"CD02", []string{"2026-06-01", "2026-06-02", "2026-06-03"}, 3},
		{"CD03", []string{"2026-06-01", "2026-06-01", "2026-06-02"}, 2},
	}
	for _, tt := range tests {
		t.Run(tt.id, func(t *testing.T) {
			if got := cumulativeDays(tt.dates); got != tt.want {
				t.Errorf("%s: cumulativeDays(%v) = %d, want %d", tt.id, tt.dates, got, tt.want)
			}
		})
	}
}
